<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="3" ignored="2" retried="4" total="17" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="320724" started-at="2020-09-01T16:44:17 IST" finished-at="2020-09-01T16:49:38 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="320724" started-at="2020-09-01T16:44:17 IST" finished-at="2020-09-01T16:49:38 IST">
      <class name="com.qa.testcases.ProductsPageTest">
        <test-method status="PASS" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321]" name="setup" is-config="true" duration-ms="6403" started-at="2020-09-01T16:47:20 IST" finished-at="2020-09-01T16:47:27 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.testcases.ProductsPageTest.sortingTest(java.lang.String,java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="sortingTest(java.lang.String, java.lang.String)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321]" name="sortingTest" duration-ms="5934" started-at="2020-09-01T16:47:27 IST" data-provider="getUserDetails" finished-at="2020-09-01T16:47:33 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[hilo]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Sauce Labs Fleece Jacket]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sortingTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321]" name="tearDown" is-config="true" duration-ms="1032" started-at="2020-09-01T16:47:33 IST" finished-at="2020-09-01T16:47:34 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=sortingTest status=SUCCESS method=ProductsPageTest.sortingTest(java.lang.String, java.lang.String)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321]" name="setup" is-config="true" duration-ms="6743" started-at="2020-09-01T16:47:34 IST" finished-at="2020-09-01T16:47:40 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.testcases.ProductsPageTest.sortingTest(java.lang.String,java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="SKIP" signature="sortingTest(java.lang.String, java.lang.String)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321]" name="sortingTest" duration-ms="7426" retried="true" started-at="2020-09-01T16:47:40 IST" data-provider="getUserDetails" finished-at="2020-09-01T16:47:48 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[lohi]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Sauce Labs OnesieM]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Sauce Labs OnesieM] but found [Sauce Labs Onesie]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Sauce Labs OnesieM] but found [Sauce Labs Onesie]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.testcases.ProductsPageTest.sortingTest(ProductsPageTest.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sortingTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321]" name="tearDown" is-config="true" duration-ms="1075" started-at="2020-09-01T16:47:48 IST" finished-at="2020-09-01T16:47:49 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=sortingTest status=SKIP method=ProductsPageTest.sortingTest(java.lang.String, java.lang.String)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321]" name="setup" is-config="true" duration-ms="6519" started-at="2020-09-01T16:47:49 IST" finished-at="2020-09-01T16:47:55 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.testcases.ProductsPageTest.sortingTest(java.lang.String,java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="sortingTest(java.lang.String, java.lang.String)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321]" name="sortingTest" duration-ms="4194" started-at="2020-09-01T16:47:55 IST" data-provider="getUserDetails" finished-at="2020-09-01T16:48:00 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[lohi]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Sauce Labs OnesieM]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Sauce Labs OnesieM] but found [Sauce Labs Onesie]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Sauce Labs OnesieM] but found [Sauce Labs Onesie]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.testcases.ProductsPageTest.sortingTest(ProductsPageTest.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sortingTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321]" name="tearDown" is-config="true" duration-ms="1070" started-at="2020-09-01T16:48:00 IST" finished-at="2020-09-01T16:48:01 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=sortingTest status=FAILURE method=ProductsPageTest.sortingTest(java.lang.String, java.lang.String)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321]" name="setup" is-config="true" duration-ms="14268" started-at="2020-09-01T16:48:01 IST" finished-at="2020-09-01T16:48:15 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.testcases.ProductsPageTest.sortingTest(java.lang.String,java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="sortingTest(java.lang.String, java.lang.String)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321]" name="sortingTest" duration-ms="38853" started-at="2020-09-01T16:48:15 IST" data-provider="getUserDetails" finished-at="2020-09-01T16:48:54 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[za]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Test.allTheThings() T-Shirt (Red)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sortingTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321]" name="tearDown" is-config="true" duration-ms="1026" started-at="2020-09-01T16:48:54 IST" finished-at="2020-09-01T16:48:55 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=sortingTest status=SUCCESS method=ProductsPageTest.sortingTest(java.lang.String, java.lang.String)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321]" name="setup" is-config="true" duration-ms="6910" started-at="2020-09-01T16:48:55 IST" finished-at="2020-09-01T16:49:02 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.testcases.ProductsPageTest.sortingTest(java.lang.String,java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="SKIP" signature="sortingTest(java.lang.String, java.lang.String)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321]" name="sortingTest" duration-ms="15269" retried="true" started-at="2020-09-01T16:49:02 IST" data-provider="getUserDetails" finished-at="2020-09-01T16:49:17 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[az]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Sauce Labs BackpackM]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Sauce Labs BackpackM] but found [Sauce Labs Backpack]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Sauce Labs BackpackM] but found [Sauce Labs Backpack]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.testcases.ProductsPageTest.sortingTest(ProductsPageTest.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sortingTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321]" name="tearDown" is-config="true" duration-ms="1025" started-at="2020-09-01T16:49:17 IST" finished-at="2020-09-01T16:49:18 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=sortingTest status=SKIP method=ProductsPageTest.sortingTest(java.lang.String, java.lang.String)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321]" name="setup" is-config="true" duration-ms="6710" started-at="2020-09-01T16:49:18 IST" finished-at="2020-09-01T16:49:25 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.testcases.ProductsPageTest.sortingTest(java.lang.String,java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="sortingTest(java.lang.String, java.lang.String)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321]" name="sortingTest" duration-ms="11283" started-at="2020-09-01T16:49:25 IST" data-provider="getUserDetails" finished-at="2020-09-01T16:49:36 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[az]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Sauce Labs BackpackM]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Sauce Labs BackpackM] but found [Sauce Labs Backpack]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Sauce Labs BackpackM] but found [Sauce Labs Backpack]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.testcases.ProductsPageTest.sortingTest(ProductsPageTest.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sortingTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321]" name="tearDown" is-config="true" duration-ms="1018" started-at="2020-09-01T16:49:37 IST" finished-at="2020-09-01T16:49:38 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=sortingTest status=FAILURE method=ProductsPageTest.sortingTest(java.lang.String, java.lang.String)[pri:0, instance:com.qa.testcases.ProductsPageTest@458c1321] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.testcases.ProductsPageTest -->
      <class name="com.qa.testcases.LoginPageTest">
        <test-method status="PASS" signature="extentReportSetup()[pri:0, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="extentReportSetup" is-config="true" duration-ms="624" started-at="2020-09-01T16:44:16 IST" finished-at="2020-09-01T16:44:17 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentReportSetup -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="setUp" is-config="true" duration-ms="10046" started-at="2020-09-01T16:44:17 IST" finished-at="2020-09-01T16:44:27 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.testcases.LoginPageTest.loginPageTitleTest()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="loginPageTitleTest()[pri:0, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="loginPageTitleTest" duration-ms="15" started-at="2020-09-01T16:44:27 IST" finished-at="2020-09-01T16:44:27 IST">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[<<< Under Maintenance >>>]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: <<< Under Maintenance >>>
at com.qa.testcases.LoginPageTest.loginPageTitleTest(LoginPageTest.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageTitleTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="tearDown" is-config="true" duration-ms="1244" started-at="2020-09-01T16:44:27 IST" finished-at="2020-09-01T16:44:28 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginPageTitleTest status=SKIP method=LoginPageTest.loginPageTitleTest()[pri:0, instance:com.qa.testcases.LoginPageTest@305fd85d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="setUp" is-config="true" duration-ms="10011" started-at="2020-09-01T16:44:28 IST" finished-at="2020-09-01T16:44:38 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.testcases.LoginPageTest.UITest()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="UITest()[pri:1, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="UITest" duration-ms="173" started-at="2020-09-01T16:44:38 IST" finished-at="2020-09-01T16:44:39 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UITest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="tearDown" is-config="true" duration-ms="1129" started-at="2020-09-01T16:44:39 IST" finished-at="2020-09-01T16:44:40 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=UITest status=SUCCESS method=LoginPageTest.UITest()[pri:1, instance:com.qa.testcases.LoginPageTest@305fd85d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="setUp" is-config="true" duration-ms="8087" started-at="2020-09-01T16:44:40 IST" finished-at="2020-09-01T16:44:48 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.testcases.LoginPageTest.stdUserLoginTest()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="stdUserLoginTest()[pri:2, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="stdUserLoginTest" duration-ms="60294" retried="true" started-at="2020-09-01T16:44:48 IST" finished-at="2020-09-01T16:45:48 IST">
          <exception class="org.openqa.selenium.TimeoutException">
            <message>
              <![CDATA[timeout: Timed out receiving message from renderer: 60.000
  (Session info: chrome=85.0.4183.83)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ARPGL000810', ip: '192.168.43.87', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 85.0.4183.83, chrome: {chromedriverVersion: 84.0.4147.30 (48b3e868b4cc0..., userDataDir: C:\Users\ROHIT_~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:58653}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 58d93eebdfcc5bc6d1f12d954bcfbdcb]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.TimeoutException: timeout: Timed out receiving message from renderer: 60.000
  (Session info: chrome=85.0.4183.83)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ARPGL000810', ip: '192.168.43.87', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 85.0.4183.83, chrome: {chromedriverVersion: 84.0.4147.30 (48b3e868b4cc0..., userDataDir: C:\Users\ROHIT_~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:58653}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 58d93eebdfcc5bc6d1f12d954bcfbdcb
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at com.sun.proxy.$Proxy12.click(Unknown Source)
at com.qa.pages.LoginPage.loginAccount(LoginPage.java:42)
at com.qa.testcases.LoginPageTest.stdUserLoginTest(LoginPageTest.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.TimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stdUserLoginTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="tearDown" is-config="true" duration-ms="1041" started-at="2020-09-01T16:45:48 IST" finished-at="2020-09-01T16:45:49 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=stdUserLoginTest status=SKIP method=LoginPageTest.stdUserLoginTest()[pri:2, instance:com.qa.testcases.LoginPageTest@305fd85d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="setUp" is-config="true" duration-ms="7131" started-at="2020-09-01T16:45:49 IST" finished-at="2020-09-01T16:45:56 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.testcases.LoginPageTest.stdUserLoginTest()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="stdUserLoginTest()[pri:2, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="stdUserLoginTest" duration-ms="9428" started-at="2020-09-01T16:45:56 IST" finished-at="2020-09-01T16:46:06 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stdUserLoginTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="tearDown" is-config="true" duration-ms="1023" started-at="2020-09-01T16:46:06 IST" finished-at="2020-09-01T16:46:07 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=stdUserLoginTest status=SUCCESS method=LoginPageTest.stdUserLoginTest()[pri:2, instance:com.qa.testcases.LoginPageTest@305fd85d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="setUp" is-config="true" duration-ms="7983" started-at="2020-09-01T16:46:07 IST" finished-at="2020-09-01T16:46:15 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.testcases.LoginPageTest.multiUserLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="multiUserLoginTest(java.lang.String, java.lang.String)[pri:3, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="multiUserLoginTest" duration-ms="9655" started-at="2020-09-01T16:46:15 IST" data-provider="getUserDetails" finished-at="2020-09-01T16:46:25 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[standard_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multiUserLoginTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="tearDown" is-config="true" duration-ms="1068" started-at="2020-09-01T16:46:25 IST" finished-at="2020-09-01T16:46:26 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=multiUserLoginTest status=SUCCESS method=LoginPageTest.multiUserLoginTest(java.lang.String, java.lang.String)[pri:3, instance:com.qa.testcases.LoginPageTest@305fd85d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="setUp" is-config="true" duration-ms="11007" started-at="2020-09-01T16:46:26 IST" finished-at="2020-09-01T16:46:37 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.testcases.LoginPageTest.multiUserLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="multiUserLoginTest(java.lang.String, java.lang.String)[pri:3, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="multiUserLoginTest" duration-ms="183" retried="true" started-at="2020-09-01T16:46:37 IST" data-provider="getUserDetails" finished-at="2020-09-01T16:46:37 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[locked_out_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.qa.pages.ProductsPage.verifyPageByURL(ProductsPage.java:35)
at com.qa.testcases.LoginPageTest.multiUserLoginTest(LoginPageTest.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multiUserLoginTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="tearDown" is-config="true" duration-ms="890" started-at="2020-09-01T16:46:37 IST" finished-at="2020-09-01T16:46:38 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=multiUserLoginTest status=SKIP method=LoginPageTest.multiUserLoginTest(java.lang.String, java.lang.String)[pri:3, instance:com.qa.testcases.LoginPageTest@305fd85d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="setUp" is-config="true" duration-ms="7559" started-at="2020-09-01T16:46:38 IST" finished-at="2020-09-01T16:46:46 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.testcases.LoginPageTest.multiUserLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="multiUserLoginTest(java.lang.String, java.lang.String)[pri:3, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="multiUserLoginTest" duration-ms="185" started-at="2020-09-01T16:46:46 IST" data-provider="getUserDetails" finished-at="2020-09-01T16:46:46 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[locked_out_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.qa.pages.ProductsPage.verifyPageByURL(ProductsPage.java:35)
at com.qa.testcases.LoginPageTest.multiUserLoginTest(LoginPageTest.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multiUserLoginTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="tearDown" is-config="true" duration-ms="1014" started-at="2020-09-01T16:46:46 IST" finished-at="2020-09-01T16:46:47 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=multiUserLoginTest status=FAILURE method=LoginPageTest.multiUserLoginTest(java.lang.String, java.lang.String)[pri:3, instance:com.qa.testcases.LoginPageTest@305fd85d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="setUp" is-config="true" duration-ms="9797" started-at="2020-09-01T16:46:47 IST" finished-at="2020-09-01T16:46:57 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.testcases.LoginPageTest.multiUserLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="multiUserLoginTest(java.lang.String, java.lang.String)[pri:3, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="multiUserLoginTest" duration-ms="3775" started-at="2020-09-01T16:46:57 IST" data-provider="getUserDetails" finished-at="2020-09-01T16:47:01 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[problem_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multiUserLoginTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="tearDown" is-config="true" duration-ms="1014" started-at="2020-09-01T16:47:01 IST" finished-at="2020-09-01T16:47:02 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=multiUserLoginTest status=SUCCESS method=LoginPageTest.multiUserLoginTest(java.lang.String, java.lang.String)[pri:3, instance:com.qa.testcases.LoginPageTest@305fd85d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="setUp" is-config="true" duration-ms="7712" started-at="2020-09-01T16:47:02 IST" finished-at="2020-09-01T16:47:09 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.testcases.LoginPageTest.multiUserLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="multiUserLoginTest(java.lang.String, java.lang.String)[pri:3, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="multiUserLoginTest" duration-ms="9757" started-at="2020-09-01T16:47:09 IST" data-provider="getUserDetails" finished-at="2020-09-01T16:47:19 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[performance_glitch_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multiUserLoginTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="tearDown" is-config="true" duration-ms="1045" started-at="2020-09-01T16:47:19 IST" finished-at="2020-09-01T16:47:20 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=multiUserLoginTest status=SUCCESS method=LoginPageTest.multiUserLoginTest(java.lang.String, java.lang.String)[pri:3, instance:com.qa.testcases.LoginPageTest@305fd85d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="extentReportCleanUp()[pri:0, instance:com.qa.testcases.LoginPageTest@305fd85d]" name="extentReportCleanUp" is-config="true" duration-ms="258" started-at="2020-09-01T16:49:38 IST" finished-at="2020-09-01T16:49:38 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentReportCleanUp -->
      </class> <!-- com.qa.testcases.LoginPageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
